version: "3.9"

services:
  supermario:
    container_name: supermario-dc
    image: kaminskypavel/mario
    ports:
      - "1033:8080"
    restart: unless-stopped
  "2048":
    container_name: 2048-game-dc
    image: marcincuber/2048-game
    ports:
      - "1034:80"
    restart: unless-stopped
  tetris:
    container_name: tetris-dc
    image: bsord/tetris
    ports:
      - "1035:80"
    restart: unless-stopped
  duck-hunt:
    container_name: duck-hunt-dc
    image: mojitoparty/duckhunt-js
    ports:
      - "1036:80"
    restart: unless-stopped